import pandas as pd
import numpy as np

def add_lags_and_rolling(df):

    # Sorting the Data chronologically per client before shifting
    print("Sorting data for lag calculations...")
    df = df.sort_values(by=['ClientID', 'Date']).reset_index(drop=True)

    # Calculate the time difference between consecutive rows for each client
    time_diffs = df.groupby('ClientID', observed=True)['Date'].diff()

    # The difference should be exactly 15 minutes, except for the first row of each client (which is NaT)
    irregular_gaps = time_diffs[(time_diffs.notnull()) & (time_diffs != pd.Timedelta(minutes=15))]

    if len(irregular_gaps) != 0:
        print(f"Warning: Found {len(irregular_gaps)} missing or irregular timestamp intervals!")
        display(df.loc[irregular_gaps.index])

    print("Calculating Lags...")
    # Create Lag Features Grouped by Client
    # EX: shift(1) = 1 step back (15 minutes ago)
    df['Lag_15min'] = df.groupby('ClientID', observed=True)['Consumption'].shift(1).astype(np.float32)
    df['Lag_1h'] = df.groupby('ClientID', observed=True)['Consumption'].shift(4).astype(np.float32)
    df['Lag_24h'] = df.groupby('ClientID', observed=True)['Consumption'].shift(96).astype(np.float32)
    df['Lag_1week'] = df.groupby('ClientID', observed=True)['Consumption'].shift(672).astype(np.float32)

    print("Calculating Rolling Windows...")
    # Create Rolling Window Features Grouped by Client
    df['Rolling_Mean_4h'] = df.groupby('ClientID', observed=True)['Consumption'].transform(
        lambda x: x.rolling(window=16).mean()
    ).astype(np.float32)

    # Drop rows with NaN values generated by the shift/rolling operations 
    print("Dropping NaNs...")
    df = df.dropna().reset_index(drop=True)

    return df