import pandas as pd
import numpy as np

def add_lags_and_rolling(df):
    """
    Performs autoregressive feature engineering by calculating historical lags 
    and rolling statistical windows for each client.
    
    This function sorts the data chronologically per client, validates the 
    consistency of the 15-minute time intervals, and generates features that 
    capture short-term, daily, and weekly consumption patterns. These features 
    allow the model to learn from past behavior (e.g., "what happened 24 hours ago?").

    Args:
        df (pd.DataFrame): The input DataFrame in 'long' format. 
                           Must contain 'ClientID', 'Date', and 'Consumption' columns.

    Returns:
        pd.DataFrame: The augmented DataFrame containing new columns:
            - 'Lag_15min': Consumption from the previous 15-min step.
            - 'Lag_1h': Consumption from 1 hour ago (4 steps).
            - 'Lag_24h': Consumption from 24 hours ago (96 steps).
            - 'Lag_1week': Consumption from 1 week ago (672 steps).
            - 'Rolling_Mean_4h': Moving average of the last 4 hours (16 steps).
            - 'HDH_lag24h': Heating degree hours from 24h ago.
            - 'CDH_lag24h': Cooling degree hours from 24h ago.
            Note: The first 672 rows of each client are dropped due to NaN values 
            generated by the furthest lag.
    """
    print("Sorting data for lag calculations...")
    df = df.sort_values(by=['ClientID', 'Date']).reset_index(drop=True)

    print("Checking for missing timestamps...")
    time_diffs = df.groupby('ClientID', observed=True)['Date'].diff()
    irregular_gaps = time_diffs[(time_diffs.notnull()) & (time_diffs != pd.Timedelta(minutes=15))]
    if len(irregular_gaps) != 0:
        print(f"Warning: Found {len(irregular_gaps)} missing or irregular timestamp intervals!")
        display(df.loc[irregular_gaps.index])

    print("Calculating Lags...")
    df['Lag_15min'] = df.groupby('ClientID', observed=True)['Consumption'].shift(1).astype(np.float32)
    df['Lag_1h'] = df.groupby('ClientID', observed=True)['Consumption'].shift(4).astype(np.float32)
    df['Lag_24h'] = df.groupby('ClientID', observed=True)['Consumption'].shift(96).astype(np.float32)
    df['Lag_1week'] = df.groupby('ClientID', observed=True)['Consumption'].shift(672).astype(np.float32)

    print("Calculating weather lags (thermal inertia)...")
    df['HDH_lag24h'] = df.groupby('ClientID', observed=True)['HDH'].shift(96).astype(np.float32)
    df['CDH_lag24h'] = df.groupby('ClientID', observed=True)['CDH'].shift(96).astype(np.float32)

    print("Calculating weather anomalies (30-day rolling baseline)...")
    df['HDH_anomaly'] = (
        df['HDH'] - df.groupby('ClientID', observed=True)['HDH'].transform(
            lambda x: x.rolling(96 * 30, min_periods=96).mean()
        )
    ).astype(np.float32)

    df['CDH_anomaly'] = (
        df['CDH'] - df.groupby('ClientID', observed=True)['CDH'].transform(
            lambda x: x.rolling(96 * 30, min_periods=96).mean()
        )
    ).astype(np.float32)

    print("Calculating Rolling Windows...")
    # Create Rolling Window Features Grouped by Client
    # Ensure the rolling window only uses PAST data (shift by 1 to avoid leakage)
    df['Rolling_Mean_4h'] = df.groupby('ClientID', observed=True)['Consumption'].transform(
        lambda x: x.shift(1).rolling(window=16).mean()
    ).astype(np.float32)

    # Drop rows with NaN values generated by the shift/rolling operations 
    print("Dropping NaNs...")
    cols_to_check = ['Lag_1week', 'Rolling_Mean_4h']
    df = df.dropna(subset=cols_to_check).reset_index(drop=True)

    return df